"""empty message

Revision ID: 832077ae6084
Revises: f6725e05f681
Create Date: 2021-03-17 14:46:01.819192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832077ae6084'
down_revision = 'f6725e05f681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('recipe', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'allergy_diet')
    op.drop_column('users', 'foodie_bio')
    op.drop_column('users', 'cooking_level')
    op.drop_column('users', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('url', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('cooking_level', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('foodie_bio', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('allergy_diet', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_table('recipes')
    # ### end Alembic commands ###
